config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'books#home', as: "home"
  get "/books", to: "books#index", as: "books"
  get "/books/new", to: "books#new", as: "new_book"
  post '/books', to: 'books#create'
  get "/books/:id", to: "books#show", as: "book"
  get "/books/:id/edit", to: "books#edit", as: "edit_book"
  patch '/books/:id', to: 'books#update'
  put '/books/:id', to: 'books#update'
  
  delete '/books/:id', to: "books#destroy", as: "delete_book"

  root to: 'books#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  
    @books = Book.all.order("created_at DESC")
  end
  
  def new
    @books = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
  
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def create
    @book = Book.new(book_params)
  
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  
  end
  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
   
    redirect_to books_path
  end
  
  
  private
  def book_params
    params.permit(:title, :author, :publisher, :genre, :description)
  end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="title-box">
    <h1>Edit Book</h1>
  </div>
  <form class="form" action="<%= book_path(params[:id]) %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <input type="hidden" name="_method" value="patch" />

    <label>Title</label>
    <input type="text" name="title" class="texter" value="<%= @book.title %>"/>

    <label>Author</label>
    <input type="text" name="author" class="texter" value="<%= @book.author %>"/>

    <label>Publisher</label>
    <input type="text" name="publisher" class="texter" value="<%= @book.publisher %>"/>
    
    <label>Genre</label>
    <input type="text" name="genre" class="texter" value="<%= @book.genre %>"/>

    <label>Description</label>
    <input type="textarea" name="description" class="description" value="<%= @book.description %>"/>

    <input type="submit" value="Update" class="create"/>
  </form>
  <%= link_to "<< Back", :back %>
  </div>

app/views/books/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Fakebook</h1>
    <p>The #1 place for Fake Book Reviews.</p>
    <a style="background-color:#222222;border:#222222;" href="/books" class="btn btn-success btn-lg">Find Books</a>
  </div>
</div>

app/views/books/index.html.erb
<div class="collection">
  <h1>Booklist</h1>
</div>
<div class="book-list">
  <% @books.each do |book| %>
  <div class="wrapper">
    <h2><%= book.title %></h2>
    <h3>Author: <%= book.author %></h3>
    <div class="button">
    <%= link_to book_path(book.id), class: "btn btn-default" do %>
      <i class="fas fa-eye"></i> 
    <% end %>
    <%= link_to edit_book_path(book.id), class: "btn btn-default" do %>
      <i class="fas fa-edit"></i> 
    <% end %>
    <%= link_to delete_book_path(book),               
            method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
      <i class="far fa-trash-alt"></i> 
    <% end %>
  </div>
</div>



  <% end %>





</div>

app/views/books/new.html.erb
<div class="container">
  <div class="title-box">
    <h1>Add Book</h1>
  </div>
  <form class="form" action="<%= books_path %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
    <label>Title</label>
    <input type="text" name="title" class="texter" />

    <label>Author</label>
    <input type="text" name="author" class="texter" />

    <label>Publisher</label>
    <input type="text" name="publisher" class="texter" />
    
    <label>Genre</label>
    <input type="text" name="genre" class="texter" />

    <label>Description</label>
    <input type="textarea" name="description" class="description" />

  
    <input type="submit" value="Create" class="create"/>
  </form>
  <%= link_to "<< Back", :back %>
</div>

app/views/books/show.html.erb
<div class="book-detail">
  <h2><%= @book.title %></h2>
  <h3>Author: <%= @book.author %></h3>
  <h3>Publisher: <%= @book.publisher %></h3>
  <h4>Genre: <%= @book.genre %></h4>
  <p>Description: <%= @book.description %></p>
  
  <%= link_to "<< Back", :back %>
  <%= link_to "Booklist >>", :books %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
</head>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to home_path, class: "btn" do %>
        <i class="fas fa-book fa-lg hover"></i> 
      <% end %>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/home">Home</a></li>
      <li><a href="/books">Booklist</a></li>
      <li><a href="/books/new">Add Book</a></li>
    </ul>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>